# Generated by Django 5.1.3 on 2024-12-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
